modLoader="javafml"
loaderVersion="[48,)"
license="All rights reserved"
issueTrackerURL="https://github.com/pokecentral"

[[mods]]
modId="deforged"
version="${file.jarVersion}"
displayName="Pixelmon Deforged"
displayURL="http://pokecentral.org/"
authors="Techdaan"
description='''
Forge coremod fixing annoying bugs in Pixelmon
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.deforged]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[48,)" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.deforged]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2]"
ordering="NONE"
side="BOTH"
[[dependencies.deforged]]
modId="pixelmon"
mandatory=true
versionRange="[9.2.6]"
ordering="AFTER"
side="BOTH"